import type { CompanyProfile, FounderProfile, OperatorProfile } from "@/hooks/useProfile";

/** Shown when the public directory query returns no rows (mock client, empty DB, or RLS). */
export const NETWORK_DIRECTORY_DEMO_FOUNDERS: FounderProfile[] = [
  {
    id: "vekta-demo-founder-1",
    user_id: "vekta-demo-founder-1",
    full_name: "Jordan Lee",
    title: "CEO & Co-founder",
    bio: "Building compliance automation for mid-market finance teams.",
    location: "San Francisco, CA",
    user_type: "founder",
    avatar_url: null,
    company_id: null,
    linkedin_url: null,
    twitter_url: null,
    resume_url: null,
    is_public: true,
    company_name: "Northline Systems",
    company_sector: "FinTech",
    company_stage: "Series A",
    company_competitors: null,
    company_website: "https://example.com",
  },
  {
    id: "vekta-demo-founder-2",
    user_id: "vekta-demo-founder-2",
    full_name: "Samira Khan",
    title: "Co-founder",
    bio: "Applied ML for industrial quality control.",
    location: "Austin, TX",
    user_type: "founder",
    avatar_url: null,
    company_id: null,
    linkedin_url: null,
    twitter_url: null,
    resume_url: null,
    is_public: true,
    company_name: "Lattice Vision",
    company_sector: "Industrial",
    company_stage: "Seed",
    company_competitors: null,
    company_website: null,
  },
  {
    id: "vekta-demo-founder-3",
    user_id: "vekta-demo-founder-3",
    full_name: "Chris Ortiz",
    title: "Founder",
    bio: "Developer tools for API reliability and observability.",
    location: "New York, NY",
    user_type: "founder",
    avatar_url: null,
    company_id: null,
    linkedin_url: null,
    twitter_url: null,
    resume_url: null,
    is_public: true,
    company_name: "Relaystack",
    company_sector: "Developer Tools",
    company_stage: "Series B",
    company_competitors: null,
    company_website: null,
  },
];

export const NETWORK_DIRECTORY_DEMO_COMPANIES: CompanyProfile[] = [
  {
    id: "vekta-demo-company-1",
    name: "Northline Systems",
    description: "Compliance automation platform for regulated finance workflows.",
    sector: "FinTech",
    city: "San Francisco",
    country: "USA",
    website: "https://example.com",
    logo_url: null,
    founded_year: 2021,
    is_yc_backed: false,
    yc_batch: null,
    employee_count: 42,
    funding_status: "vc_backed",
    vc_backed: true,
    investment_stage: "Series A",
  },
  {
    id: "vekta-demo-company-2",
    name: "Lattice Vision",
    description: "Computer vision for factory floor defect detection.",
    sector: "Industrial",
    city: "Austin",
    country: "USA",
    website: null,
    logo_url: null,
    founded_year: 2023,
    is_yc_backed: true,
    yc_batch: "W24",
    employee_count: 18,
    funding_status: "vc_backed",
    vc_backed: true,
    investment_stage: "Seed",
  },
  {
    id: "vekta-demo-company-3",
    name: "Relaystack",
    description: "Synthetic monitoring and chaos testing for APIs.",
    sector: "Developer Tools",
    city: "New York",
    country: "USA",
    website: null,
    logo_url: null,
    founded_year: 2020,
    is_yc_backed: false,
    yc_batch: null,
    employee_count: 65,
    funding_status: "vc_backed",
    vc_backed: true,
    investment_stage: "Series B",
  },
];

export const NETWORK_DIRECTORY_DEMO_OPERATORS: OperatorProfile[] = [
  {
    id: "vekta-demo-operator-1",
    full_name: "Morgan Ellis",
    title: "Fractional CFO",
    bio: "Seed to Series B finance, forecasting, and board reporting.",
    avatar_url: null,
    linkedin_url: null,
    x_url: null,
    city: "Denver",
    state: "CO",
    country: "USA",
    engagement_type: "fractional",
    sector_focus: ["SaaS", "FinTech"],
    stage_focus: "Seed — Series A",
    expertise: ["FP&A", "Fundraising"],
    prior_companies: ["Stripe", "Carta"],
    is_available: true,
  },
  {
    id: "vekta-demo-operator-2",
    full_name: "Priya Shah",
    title: "VP Engineering (advisor)",
    bio: "Scaling eng orgs from 10 to 120; hiring systems and architecture reviews.",
    avatar_url: null,
    linkedin_url: null,
    x_url: null,
    city: "Seattle",
    state: "WA",
    country: "USA",
    engagement_type: "advisory",
    sector_focus: ["B2B SaaS"],
    stage_focus: "Series A+",
    expertise: ["Platform", "Security"],
    prior_companies: ["Datadog"],
    is_available: true,
  },
];
