import type { ComboboxOption } from "@/components/ui/smart-combobox";

export const ROLE_OPTIONS: ComboboxOption[] = [
  // Executive & Founding
  { value: "CEO", label: "CEO", desc: "Founder, Managing Director, President" },
  { value: "CEO & Founder", label: "CEO & Founder", desc: "Chief Executive Officer" },
  { value: "CEO & Co-Founder", label: "CEO & Co-Founder", desc: "Co-founded the company" },
  { value: "CTO", label: "CTO", desc: "VP Engineering, Technical Co-Founder" },
  { value: "CTO & Co-Founder", label: "CTO & Co-Founder", desc: "Technical co-founder" },
  { value: "COO", label: "COO", desc: "VP Ops, Head of Ops, General Manager" },
  { value: "CPO", label: "CPO", desc: "Head of Product, VP Product" },
  { value: "CFO", label: "CFO", desc: "Finance Director, VP Finance" },
  { value: "CMO", label: "CMO", desc: "Head of Growth, VP Marketing" },
  { value: "Chief of Staff", label: "Chief of Staff", desc: "CEO's Right Hand, Operations Lead" },
  { value: "CRO", label: "CRO", desc: "Head of Sales, VP Global Sales" },
  { value: "Chief People Officer", label: "Chief People Officer", desc: "Head of Talent, Culture Lead" },
  { value: "Chief Automation Officer", label: "Chief Automation Officer", desc: "AI Workflow Lead" },
  { value: "Chief Storytelling Officer", label: "Chief Storytelling Officer", desc: "Brand/Creative Lead" },
  { value: "Chief Rainmaker", label: "Chief Rainmaker", desc: "High-performing Sales Director" },
  { value: "Chief Satisfaction Officer", label: "Chief Satisfaction Officer", desc: "Head of CS" },

  // C-Level & Executive Titles
  { value: "VP of Engineering", label: "VP of Engineering", desc: "Engineering executive" },
  { value: "VP of Operations", label: "VP of Operations", desc: "Operations executive" },
  { value: "VP of Product", label: "VP of Product", desc: "Product leadership" },
  { value: "VP of Marketing", label: "VP of Marketing", desc: "Growth and brand leadership" },
  { value: "VP of Sales", label: "VP of Sales", desc: "Sales and revenue leadership" },
  { value: "VP of Finance", label: "VP of Finance", desc: "Finance executive" },
  { value: "Head of Product", label: "Head of Product", desc: "Product leadership" },
  { value: "Head of Engineering", label: "Head of Engineering", desc: "Engineering leadership" },
  { value: "Head of Sales", label: "Head of Sales", desc: "Sales leadership" },
  { value: "Head of Content", label: "Head of Content", desc: "Editorial lead" },
  { value: "Head of Growth", label: "Head of Growth", desc: "Growth marketing lead" },
  { value: "Head of Talent", label: "Head of Talent", desc: "Recruitment and HR" },
  { value: "Head of Ops", label: "Head of Ops", desc: "Operations leadership" },

  // Engineering - The Builders
  { value: "Software Engineer", label: "Software Engineer", desc: "Developer, Coder, IC" },
  { value: "Founding Engineer", label: "Founding Engineer", desc: "First Engineer, Lead Dev" },
  { value: "Full-Stack Engineer", label: "Full-Stack Engineer", desc: "Product Engineer, Generalist" },
  { value: "Backend Engineer", label: "Backend Engineer", desc: "Systems Engineer, API Architect" },
  { value: "Frontend Engineer", label: "Frontend Engineer", desc: "UI Engineer, Interface Developer" },
  { value: "Mobile Engineer", label: "Mobile Engineer", desc: "iOS/Android Developer, Flutter/React Native" },
  { value: "iOS Developer", label: "iOS Developer", desc: "iOS Engineer" },
  { value: "Android Developer", label: "Android Developer", desc: "Android Engineer" },
  { value: "React Native Engineer", label: "React Native Engineer", desc: "Cross-platform mobile" },
  { value: "Flutter Developer", label: "Flutter Developer", desc: "Cross-platform mobile" },
  { value: "DevOps Engineer", label: "DevOps Engineer", desc: "Infrastructure Engineer, Platform Lead" },
  { value: "SRE", label: "SRE", desc: "Site Reliability Engineer, Infrastructure" },
  { value: "Security Engineer", label: "Security Engineer", desc: "DevSecOps, InfoSec Analyst" },
  { value: "QA Engineer", label: "QA Engineer", desc: "SDET, Quality Lead" },
  { value: "Staff Engineer", label: "Staff Engineer", desc: "High-level Technical IC" },
  { value: "Principal Engineer", label: "Principal Engineer", desc: "High-level Technical IC" },

  // AI & Data - The 2026 Core
  { value: "AI Engineer", label: "AI Engineer", desc: "ML Specialist, Model Architect" },
  { value: "AI/ML Engineer", label: "AI/ML Engineer", desc: "ML Specialist, Model Architect" },
  { value: "LLMOps Engineer", label: "LLMOps Engineer", desc: "AI Infra, Prompt Engineer" },
  { value: "Prompt Engineer", label: "Prompt Engineer", desc: "LLM specialist" },
  { value: "Data Scientist", label: "Data Scientist", desc: "AI Researcher, Quant" },
  { value: "Data Engineer", label: "Data Engineer", desc: "Pipeline Architect, Analytics Engineer" },
  { value: "AI Ethicist", label: "AI Ethicist", desc: "Trust & Safety, Governance Lead" },
  { value: "Data Analyst", label: "Data Analyst", desc: "BI Analyst, Product Analyst" },
  { value: "Computer Vision Engineer", label: "Computer Vision Engineer", desc: "Perception Engineer" },
  { value: "NLP Engineer", label: "NLP Engineer", desc: "Text/Language Model Specialist" },
  { value: "Robotics Software Engineer", label: "Robotics Software Engineer", desc: "Automation/Hardware Integration" },
  { value: "Augmented Intelligence Orchestrator", label: "Augmented Intelligence Orchestrator", desc: "Human-AI Workflow Lead" },

  // Product & Design
  { value: "Product Manager", label: "Product Manager", desc: "Product Owner, Feature Lead" },
  { value: "Founding PM", label: "Founding PM", desc: "First PM, Product Lead" },
  { value: "Associate Product Manager", label: "Associate Product Manager", desc: "Junior PM, Product Coordinator" },
  { value: "Technical Product Manager", label: "Technical Product Manager", desc: "Platform PM, Eng-Product Bridge" },
  { value: "Product Designer", label: "Product Designer", desc: "UI/UX, Experience Designer" },
  { value: "Founding Designer", label: "Founding Designer", desc: "Design Lead, Creative Director" },
  { value: "UX Researcher", label: "UX Researcher", desc: "User Researcher, Insights Specialist" },
  { value: "Interaction Designer", label: "Interaction Designer", desc: "Motion Designer, UI Specialist" },
  { value: "Empathy Engineer", label: "Empathy Engineer", desc: "Emotional UX Specialist" },
  { value: "Product Ops", label: "Product Ops", desc: "Tools & Process Lead" },

  // Growth & Marketing
  { value: "Growth Marketer", label: "Growth Marketer", desc: "Performance Marketer, Growth Hacker" },
  { value: "Content Strategist", label: "Content Strategist", desc: "Head of Content, Editorial Lead" },
  { value: "Social Media Manager", label: "Social Media Manager", desc: "Viral Lead, Community Content" },
  { value: "Copywriter", label: "Copywriter", desc: "Brand Writer, Narrative Designer" },
  { value: "SEO Specialist", label: "SEO Specialist", desc: "Organic Growth, Search Strategist" },
  { value: "Product Marketing Manager", label: "Product Marketing Manager", desc: "GTM Specialist, Launch Lead" },
  { value: "Brand Manager", label: "Brand Manager", desc: "Creative Strategist" },
  { value: "Lifecycle Marketer", label: "Lifecycle Marketer", desc: "CRM, Retention Specialist" },
  { value: "Paid Acquisition Manager", label: "Paid Acquisition Manager", desc: "Media Buyer, Ad Ops" },
  { value: "Marketing Manager", label: "Marketing Manager", desc: "General marketing leadership" },

  // Sales & Business Development
  { value: "SDR", label: "SDR", desc: "Sales Development Rep, Lead Gen" },
  { value: "BDR", label: "BDR", desc: "Business Development Rep, Outbound" },
  { value: "Account Executive", label: "Account Executive", desc: "Closer, Solutions Consultant" },
  { value: "Enterprise Account Executive", label: "Enterprise Account Executive", desc: "Strategic Sales, Global Accounts" },
  { value: "Founding Sales", label: "Founding Sales", desc: "First Sales Hire, Head of New Business" },
  { value: "Partnerships Manager", label: "Partnerships Manager", desc: "Channel Manager, Strategic Alliances" },
  { value: "Sales Engineer", label: "Sales Engineer", desc: "Solutions Architect, Tech Sales" },
  { value: "Revenue Operations Manager", label: "Revenue Operations Manager", desc: "Sales Ops, CRM Manager" },
  { value: "Sales Enablement Manager", label: "Sales Enablement Manager", desc: "Sales Trainer, Coaching Lead" },

  // Customer Experience
  { value: "Customer Success Manager", label: "Customer Success Manager", desc: "Account Manager, Client Partner" },
  { value: "Support Specialist", label: "Support Specialist", desc: "Support Hero, Happiness Lead" },
  { value: "Founding Support", label: "Founding Support", desc: "First Support Hire, Head of CX" },
  { value: "Technical Support", label: "Technical Support", desc: "Tier 2 Support, Implementation" },
  { value: "Community Manager", label: "Community Manager", desc: "Discord Lead, Ecosystem Lead" },
  { value: "CX Designer", label: "CX Designer", desc: "Journey Architect" },
  { value: "Onboarding Specialist", label: "Onboarding Specialist", desc: "Implementation Lead" },
  { value: "Customer Education Manager", label: "Customer Education Manager", desc: "Documentation Specialist" },
  { value: "Renewals Manager", label: "Renewals Manager", desc: "Retention Specialist" },

  // Ops, HR & Finance
  { value: "Operations Manager", label: "Operations Manager", desc: "BizOps, Generalist Operator" },
  { value: "Strategy & Ops", label: "Strategy & Ops", desc: "Special Projects Lead" },
  { value: "People Operations Manager", label: "People Operations Manager", desc: "HR Generalist, Employee Experience" },
  { value: "Technical Recruiter", label: "Technical Recruiter", desc: "Talent Scout" },
  { value: "Founding Recruiter", label: "Founding Recruiter", desc: "First Talent Hire" },
  { value: "Finance Manager", label: "Finance Manager", desc: "Controller, Fiscal Lead" },
  { value: "Accounting Manager", label: "Accounting Manager", desc: "Finance operations" },
  { value: "General Counsel", label: "General Counsel", desc: "Legal Counsel, Legal Ops" },
  { value: "Compliance Officer", label: "Compliance Officer", desc: "Risk Manager, Regulatory Lead" },
  { value: "Office Manager", label: "Office Manager", desc: "Workplace Experience, Vibes Manager" },
  { value: "Work Rhythm Manager", label: "Work Rhythm Manager", desc: "Remote/Hybrid Productivity Lead" },

  // Specialized Sectors
  { value: "Blockchain Engineer", label: "Blockchain Engineer", desc: "Smart Contract/Solidity Dev" },
  { value: "Web3 Product Manager", label: "Web3 Product Manager", desc: "Protocol PM, Ecosystem Architect" },
  { value: "Web3 Security Engineer", label: "Web3 Security Engineer", desc: "Smart Contract Auditor" },
  { value: "Climate Impact Lead", label: "Climate Impact Lead", desc: "Sustainability Lead, ESG" },
  { value: "Carbon Procurement Manager", label: "Carbon Procurement Manager", desc: "Emissions Strategist" },
  { value: "Bioinformatics Engineer", label: "Bioinformatics Engineer", desc: "Health Data/Genomics Lead" },
  { value: "Clinical Coordinator", label: "Clinical Coordinator", desc: "Patient Success (Healthtech)" },
  { value: "Virtual Health Coach", label: "Virtual Health Coach", desc: "Wellness Orchestrator" },
  { value: "DePIN Infra Lead", label: "DePIN Infra Lead", desc: "Decentralized Physical Infra Lead" },
  { value: "Metaverse Researcher", label: "Metaverse Researcher", desc: "Virtual World Architect" },

  // Flavor & Level Variations
  { value: "Managing Partner", label: "Managing Partner", desc: "Fund or firm partner" },
  { value: "General Partner", label: "General Partner", desc: "GP at a fund" },
  { value: "Solo Founder", label: "Solo Founder", desc: "Single founder" },
  { value: "Fractional Executive", label: "Fractional Executive", desc: "Part-time/Contract C-suite" },
  { value: "Entrepreneur in Residence", label: "Entrepreneur in Residence", desc: "EIR" },
  { value: "Full-Stack Magician", label: "Full-Stack Magician", desc: "Engineer/Designer Hybrid" },
  { value: "Chief Evangelist", label: "Chief Evangelist", desc: "Brand Advocate" },
  { value: "Scrum Master", label: "Scrum Master", desc: "Agile Coach, Delivery Lead" },
  { value: "Individual Contributor", label: "Individual Contributor", desc: "Non-management track" },
  { value: "Lead Developer", label: "Lead Developer", desc: "Mentorship-focused Senior" },
  { value: "Consultant", label: "Consultant", desc: "External advisor" },
  { value: "Advisor", label: "Advisor", desc: "Strategic guidance" },
];
