// This file is automatically generated. Do not edit it directly.
import { createClient } from "@supabase/supabase-js";
import type { Database } from "./types";
import { mockSupabase } from "./mock-client";

const SUPABASE_URL = import.meta.env.VITE_SUPABASE_URL;
const SUPABASE_PUBLISHABLE_KEY = import.meta.env.VITE_SUPABASE_PUBLISHABLE_KEY;
const hasSupabaseConfig = Boolean(SUPABASE_URL && SUPABASE_PUBLISHABLE_KEY);

/** True when the real Supabase client is used (not the local mock). */
export const isSupabaseConfigured = hasSupabaseConfig;

if (import.meta.env.DEV && !hasSupabaseConfig) {
  console.warn(
    "[Supabase] Missing VITE_SUPABASE_URL or VITE_SUPABASE_PUBLISHABLE_KEY. Falling back to Mock Storage mode so the UI can function in local dev. Data will be saved to your browser's local storage."
  );
}

let accessTokenGetter: () => Promise<string | null> = async () => null;

/** Called from AuthProvider when the signed-in session changes. */
export function setSupabaseAccessTokenGetter(fn: (() => Promise<string | null>) | null) {
  accessTokenGetter = fn ?? (async () => null);
}

/** Current user JWT sent to Supabase - use for edge functions that need the signed-in user. */
export async function getSupabaseAccessToken(): Promise<string | null> {
  try {
    return await accessTokenGetter();
  } catch {
    return null;
  }
}

/**
 * `Authorization` value for Edge Functions: signed-in Supabase session JWT when available,
 * else publishable key. Misconfigured JWTs are rejected (e.g. PGRST301).
 */
export async function getSupabaseBearerForFunctions(): Promise<string | null> {
  const user = (await getSupabaseAccessToken())?.trim();
  const anon =
    typeof SUPABASE_PUBLISHABLE_KEY === "string" ? SUPABASE_PUBLISHABLE_KEY.trim() : "";
  const t = user || anon;
  return t || null;
}

const sharedAuthOptions = {
  auth: {
    persistSession: false,
    autoRefreshToken: false,
    detectSessionInUrl: false,
    storage: {
      getItem: () => null,
      setItem: () => {},
      removeItem: () => {},
    },
  },
} as const;

export const supabaseAuth = hasSupabaseConfig
  ? createClient<Database>(SUPABASE_URL!, SUPABASE_PUBLISHABLE_KEY!, {
      global: {
        fetch: (...args) => fetch(...args),
      },
      auth: {
        persistSession: true,
        autoRefreshToken: true,
        detectSessionInUrl: true,
        storageKey: "vekta-supabase-auth",
      },
    })
  : mockSupabase;

/**
 * Used for VC directory reads. Passes the user JWT when available (→ `authenticated` role),
 * falling back to `anon` when unauthenticated. Both roles have SELECT policies on `vc_*` tables.
 */
export const supabaseVcDirectory = hasSupabaseConfig
  ? createClient<Database>(SUPABASE_URL!, SUPABASE_PUBLISHABLE_KEY!, {
      global: {
        fetch: (...args) => fetch(...args),
      },
      accessToken: async () => {
        try {
          return await accessTokenGetter();
        } catch (e) {
          console.warn("[SupabaseVcDirectory] accessToken failed", e);
          return null;
        }
      },
      ...sharedAuthOptions,
    })
  : mockSupabase;

/**
 * Public Network directory reads (`organizations`, `people`, `roles`, `operator_profiles`).
 * Always uses the **publishable (anon) role** - no user JWT on the wire.
 *
 * Why: PostgREST rejects unknown JWTs with `PGRST301` ("JWT cryptographic operation failed").
 * `supabaseVcDirectory` forwards the user JWT for `vc_*` / firm flows; that same token
 * must **not** be sent for tables that only have anon/public SELECT policies, or every query
 * returns 401 and the UI shows empty grids.
 */
export const supabasePublicDirectory = hasSupabaseConfig
  ? createClient<Database>(SUPABASE_URL!, SUPABASE_PUBLISHABLE_KEY!, {
      global: {
        fetch: (...args) => fetch(...args),
      },
      ...sharedAuthOptions,
    })
  : mockSupabase;

// Export either the real client or our mock
export const supabase = hasSupabaseConfig
  ? createClient<Database>(SUPABASE_URL!, SUPABASE_PUBLISHABLE_KEY!, {
      global: {
        fetch: (...args) => fetch(...args),
      },
      // Never throw: a rejected accessToken aborts fetchWithAuth and surfaces as "Failed to send" on Edge Functions.
      accessToken: async () => {
        try {
          return await accessTokenGetter();
        } catch (e) {
          console.warn("[Supabase] accessToken failed", e);
          return null;
        }
      },
      ...sharedAuthOptions,
    })
  : mockSupabase;
