// This file is automatically generated. Do not edit it directly.
import { createClient } from "@supabase/supabase-js";
import type { Database } from "./types";

const SUPABASE_URL = import.meta.env.VITE_SUPABASE_URL;
const SUPABASE_PUBLISHABLE_KEY = import.meta.env.VITE_SUPABASE_PUBLISHABLE_KEY;

let accessTokenGetter: (() => Promise<string | null>) | null = null;

/** Called from AuthProvider when using Clerk — forwards JWT to PostgREST (third-party auth). */
export function setSupabaseAccessTokenGetter(getter: (() => Promise<string | null>) | null) {
  accessTokenGetter = getter;
}

// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    persistSession: false,
    autoRefreshToken: false,
    detectSessionInUrl: false,
  },
  global: {
    fetch: async (input, init = {}) => {
      const headers = new Headers(init.headers);
      if (accessTokenGetter) {
        try {
          const token = await accessTokenGetter();
          if (token) headers.set("Authorization", `Bearer ${token}`);
        } catch {
          /* ignore */
        }
      }
      return fetch(input, { ...init, headers });
    },
  },
});
